language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt --use-mirrors"
# command to run tests
script:
  - git submodule update --init
  - touch ncs/base/__init__.py ncs/base/pyncs.py
  - sudo mkdir /var/ncs
  - sudo chown ${USER}:${USER} /var/ncs
  - sudo apt-get install nodejs
  - sudo npm install -g jsontools
  - find json -name \*.json -exec json -n -f {} \;
  - nosetests --with-coverage --cover-package=ncsdaemon ncsdaemon/tests/*.py
# no pesky email notifications
notifications:
  email: false
# setup environment
env:
  - PYTHONPATH="${PYTHONPATH}:${TRAVIS_BUILD_DIR}/ncs/python:${TRAVIS_BUILD_DIR}/ncs/base:${TRAVIS_BUILD_DIR}/src/ncsdaemon"
after_script:
  coveralls
