language: python
python:
  - "2.7"
# command to install dependencies
install:
    - "pip install -r requirements.txt"
    - "pip install -r requirements-test.txt"
# lets add mongo
services:
  - mongodb
# command to run tests
script: make test
# no pesky email notifications
notifications:
  email: false
# setup environment
env:
  - PYTHONPATH="${PYTHONPATH}:${TRAVIS_BUILD_DIR}/ncs/python:${TRAVIS_BUILD_DIR}/ncs/base:${TRAVIS_BUILD_DIR}/src/ncsdaemon"
after_script:
  coveralls
