language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt --use-mirrors"
# command to run tests
script:
  nosetests --with-coverage --cover-package=ncsdaemon ncsdaemon/tests/*.py
# no pesky email notifications
notifications:
  email: false
# setup environment
env:
  - PYTHONPATH="${PYTHONPATH}:${PWD}/ncs/python"
after_success:
  coveralls
